# Pipeline to build and push Docker image to Docker Hub when there are changes in the main branch
# Going to use actions from -> https://github.com/marketplace?query=docker
name: Build and Push Image to DockerHub
run-name: Build and Push Image to DockerHub
on:
  # The code get pushed when the pull request is merged to the main branch from another branch
  # So, we are going to trigger this workflow when the code is pushed to the main branch
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  docker:
    name: Build and Push Docker Image to DockerHub
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout
        uses: actions/checkout@v4
      # Ubuntu-latest has Docker pre-installed
      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}} # Docker Hub username
          password: ${{secrets.DOCKER_PASSWORD}} # Docker Hub password
      # Build the Docker image
      - name: Build & Push the Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: itzzjb/docker-react:latest
  deploy:
    needs: docker
    name: Deploy to EC2
    # We have self hosted a EC2 instance as a runner from the repository settings
    # Now, we are going to use that runner to deploy the Docker image to the EC2 instance
    # We can manually installed Docker on the EC2 instance
    runs-on: self-hosted
    steps:
      - name: Pull the Docker Image
        run: sudo docker pull itzzjb/docker-react:latest
      - name: Remove the existing container
        # rm -f -> Remove the container forcefully
        # We need to set || true to ignore the error if the container does not exist
        run: sudo docker rm -f docker-react || true
      - name: Run the Docker Container
        run: sudo docker run -d -p 3000:3000 --name docker-react itzzjb/docker-react:latest
