# Pipeline to build and push Docker image to Docker Hub when there are changes in the main branch
# Going to use actions from -> https://github.com/marketplace?query=docker
name: Build and Push Image to DockerHub
run-name: Build and Push Image to DockerHub
on:
  # Pushed when the pull request is merged to the main branch from another branch
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  docker:
    name: Build and Push Docker Image to DockerHub
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout
        uses: actions/checkout@v4
      # Ubuntu-latest has Docker pre-installed
      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}} # Docker Hub username
          password: ${{secrets.DOCKER_PASSWORD}} # Docker Hub password
      # Build the Docker image
      - name: Build & Push the Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: itzzjb/docker-react:latest
