# Workflow to scan npm vulnerabilities
name: Scan npm Vulnerabilities
run-name: Scan npm Vulnerabilities
on: workflow_dispatch
jobs:
  npm-vulnerabilities:
    name: Scan npm Vulnerabilities
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      # Audit npm vulnerabilities and generate a report
      - name: Audit npm vulnerabilities and generate report
        # Can't use `npm audit --json > npm-audit-report.json` here.
        run: npm audit --json | tee npm-audit-report.json
      # Upload the report as an artifact so that it can be downloaded
      - name: Upload npm audit report
        uses: actions/upload-artifact@v2
        with:
          name: Vulnerability Report
          path: npm-audit-report.json
